# Railway Deployment Configuration for OpenClaw Multi-Agent System
# This file configures the moltbot gateway service, Neo4j database, and Authentik
# Reference: moltbot.json shows gateway runs on port 18789

# =============================================================================
# SERVICES CONFIGURATION
# =============================================================================

services:
  # ===========================================================================
  # MIGRATION RUNNER - One-shot Neo4j migration service
  # ===========================================================================
  migrations:
    build:
      context: ./railway-migrations
      dockerfile: Dockerfile

    # Environment variables
    envFile: .env

    # Environment variables for Neo4j connection
    environment:
      # Neo4j Connection (use Railway internal DNS)
      - name: NEO4J_URI
        value: "bolt://neo4j.railway.internal:7687"
      - name: NEO4J_USER
        value: "neo4j"
      # NEO4J_PASSWORD inherited from Railway variables

    # This is a one-shot job - it will exit after migrations complete
    # No health check needed

    # Dependencies - ensure Neo4j starts first
    dependsOn:
      - neo4j

  # ===========================================================================
  # MOLTBOT SERVICE - Main OpenClaw Gateway
  # ===========================================================================
  moltbot:
    build:
      context: ./moltbot-railway-template
      dockerfile: Dockerfile

    # Port configuration - OpenClaw gateway on 18789, Express API on 8082
    ports:
      - port: 18789
        targetPort: 18789
        protocol: TCP
        description: "OpenClaw Gateway"
      - port: 8082
        targetPort: 8082
        protocol: TCP
        description: "Express API Server"

    # Health check endpoint (OpenClaw built-in)
    healthcheck:
      path: /health
      port: 18789
      interval: 30s
      timeout: 10s
      startPeriod: 120s
      retries: 5

    # Environment variables from .env file
    envFile: .env

    # Additional environment variables
    environment:
      # OpenClaw Gateway Configuration
      - name: OPENCLAW_GATEWAY_PORT
        value: "18789"
      - name: OPENCLAW_STATE_DIR
        value: "/data/.openclaw"
      # OPENCLAW_GATEWAY_TOKEN should be set via Railway dashboard
      # ANTHROPIC_API_KEY should be set via Railway dashboard

      # Neo4j Connection
      - name: NEO4J_URI
        value: "bolt://neo4j.railway.internal:7687"
      - name: NEO4J_USER
        value: "neo4j"
      # NEO4J_PASSWORD should be set via Railway dashboard

      # Signal Configuration
      - name: SIGNAL_ENABLED
        value: "true"
      - name: SIGNAL_DATA_DIR
        value: "/data/.signal"
      - name: SIGNAL_CLI_PATH
        value: "/usr/local/bin/signal-cli"
      # SIGNAL_ACCOUNT should be set via Railway dashboard

      # Python configuration (for migrations)
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: PYTHONDONTWRITEBYTECODE
        value: "1"

    # Resource allocation
    resources:
      cpu: 1
      memory: 2Gi

    # Volume mounts for persistent data
    volumes:
      - name: clawdbot-data
        mountPath: /data

    # Restart policy
    restart: unless-stopped

    # Dependencies - ensure Neo4j starts first
    dependsOn:
      - neo4j

    # Cron schedule for unified heartbeat
    schedules:
      - name: kurultai-heartbeat
        cron: "*/5 * * * *"  # Every 5 minutes
        command: "cd /app && python tools/kurultai/heartbeat_master.py --cycle"
      - name: jochi-smoke-tests
        cron: "*/15 * * * *"  # Every 15 minutes
        command: "cd /app && python tools/kurultai/test_runner_orchestrator.py --phase fixtures --phase integration --dry-run"
      - name: jochi-hourly-tests
        cron: "0 * * * *"  # Every hour
        command: "cd /app && python tools/kurultai/test_runner_orchestrator.py --dry-run"
      - name: jochi-nightly-tests
        cron: "0 2 * * *"  # 2 AM daily
        command: "cd /app && python tools/kurultai/test_runner_orchestrator.py --phase all --dry-run"
      - name: kublai-weekly-reflection
        cron: "0 20 * * 0"  # Sundays at 8 PM ET
        command: "cd /app && curl -X POST http://localhost:8082/api/reflection/trigger -H 'Content-Type: application/json' -d '{}' || echo 'Reflection trigger endpoint not available'"

  # ===========================================================================
  # SKILL SYNC SERVICE - GitHub skill synchronization worker
  # ===========================================================================
  # Syncs skills from GitHub repo to shared /data/skills directory
  # Both moltbot and skill-sync-service mount the same clawdbot-data volume
  skill-sync-service:
    build:
      context: ./skill-sync-service
      dockerfile: Dockerfile

    # Health check endpoint
    healthcheck:
      path: /health
      port: 3000
      interval: 30s
      timeout: 10s
      startPeriod: 30s
      retries: 5

    # Environment variables
    envFile: .env

    environment:
      # Service Configuration
      - name: PORT
        value: "3000"
      - name: NODE_ENV
        value: production
      - name: LOG_LEVEL
        value: info

      # Skill Storage - shared with moltbot via clawdbot-data volume
      - name: SKILLS_DIR
        value: /data/skills
      - name: BACKUP_DIR
        value: /data/backups/skills
      - name: MAX_SKILL_SIZE_BYTES
        value: "102400"

      # GitHub Configuration
      - name: GITHUB_OWNER
        value: Danservfinn
      - name: GITHUB_REPO
        value: kurultai-skills
      - name: POLLING_INTERVAL_MIN
        value: "5"
      # GITHUB_WEBHOOK_SECRET and GITHUB_TOKEN set via Railway dashboard

      # Neo4j Audit Logging (shared with other services)
      - name: NEO4J_URI
        value: bolt://neo4j.railway.internal:7687
      - name: NEO4J_USER
        value: neo4j
      # NEO4J_PASSWORD set via Railway dashboard

      # Deployment Lock
      - name: DEPLOYMENT_LOCK_TTL
        value: "300"

    # Resource allocation
    resources:
      cpu: 0.5
      memory: 512Mi

    # CRITICAL: Shared volume with moltbot - same name and mount path
    # This allows skill-sync-service to write to /data/skills and moltbot to read
    volumes:
      - name: clawdbot-data
        mountPath: /data

    # Restart policy
    restart: unless-stopped

    # Dependencies - ensure Neo4j is ready for audit logging
    dependsOn:
      - neo4j

  # ===========================================================================
  # NEO4J SERVICE - Graph Database
  # ===========================================================================
  neo4j:
    image: neo4j:5-community

    # Port configuration
    ports:
      - port: 7474
        targetPort: 7474
        protocol: TCP
        description: "Neo4j HTTP Browser"
      - port: 7687
        targetPort: 7687
        protocol: TCP
        description: "Neo4j Bolt Protocol"

    # Health check using Neo4j 5 HTTP endpoint
    healthcheck:
      path: /
      port: 7474
      interval: 30s
      timeout: 10s
      startPeriod: 60s
      retries: 5

    # Environment variables for Neo4j configuration
    environment:
      # Authentication (format: neo4j/password)
      # IMPORTANT: Set NEO4J_USER and NEO4J_PASSWORD via Railway dashboard
      - name: NEO4J_AUTH
        value: ${NEO4J_USER}/${NEO4J_PASSWORD}

      # Plugins (APOC only - GDS requires Enterprise Edition)
      - name: NEO4J_PLUGINS
        value: '["apoc"]'

      # Memory settings (adjust based on Railway plan)
      - name: NEO4J_dbms_memory_heap_initial__size
        value: "512m"
      - name: NEO4J_dbms_memory_heap_max__size
        value: "1G"
      - name: NEO4J_dbms_memory_pagecache_size
        value: "512m"

      # Accept license for enterprise features (if using enterprise edition)
      # - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      #   value: "yes"

      # Enable remote connections on both IPv4 and IPv6
      # "::" enables dual-stack (IPv4 + IPv6) - required for Railway internal networking
      - name: NEO4J_dbms_default__listen__address
        value: "::"

      # Logging configuration
      - name: NEO4J_dbms_logs_debug_level
        value: "INFO"

    # Resource allocation
    resources:
      cpu: 1
      memory: 2Gi

    # Volume mounts for data persistence
    volumes:
      - name: neo4j-data
        mountPath: /data
      - name: neo4j-logs
        mountPath: /logs

    # Restart policy
    restart: unless-stopped

  # ===========================================================================
  # AUTHENTIK DATABASE - PostgreSQL for Authentik
  # ===========================================================================
  authentik-db:
    image: postgres:15-alpine

    # Health check for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTHENTIK_POSTGRESQL__USER} -d ${AUTHENTIK_POSTGRESQL__NAME}"]
      interval: 10s
      timeout: 5s
      startPeriod: 30s
      retries: 5

    # Environment variables
    environment:
      - name: POSTGRES_USER
        value: ${AUTHENTIK_POSTGRESQL__USER}
      - name: POSTGRES_PASSWORD
        value: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      - name: POSTGRES_DB
        value: ${AUTHENTIK_POSTGRESQL__NAME}

    # Resource allocation
    resources:
      cpu: 0.5
      memory: 512Mi

    # Volume mounts for data persistence
    volumes:
      - name: authentik-db-data
        mountPath: /var/lib/postgresql/data

    # Restart policy
    restart: unless-stopped

  # ===========================================================================
  # AUTHENTIK SERVER - Identity Provider
  # ===========================================================================
  authentik-server:
    build:
      context: ./authentik-server
      dockerfile: Dockerfile

    # Port configuration
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        description: "Authentik HTTP API"
      - port: 9443
        targetPort: 9443
        protocol: TCP
        description: "Authentik HTTPS API"

    # Health check
    healthcheck:
      path: /-/health/ready/
      port: 9000
      interval: 30s
      timeout: 10s
      startPeriod: 120s
      retries: 5

    # Environment variables
    environment:
      # Database connection
      - name: AUTHENTIK_POSTGRESQL__HOST
        value: authentik-db.railway.internal
      - name: AUTHENTIK_POSTGRESQL__NAME
        value: ${AUTHENTIK_POSTGRESQL__NAME}
      - name: AUTHENTIK_POSTGRESQL__USER
        value: ${AUTHENTIK_POSTGRESQL__USER}
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        value: ${AUTHENTIK_POSTGRESQL__PASSWORD}

      # Security
      - name: AUTHENTIK_SECRET_KEY
        value: ${AUTHENTIK_SECRET_KEY}
      - name: AUTHENTIK_BOOTSTRAP_PASSWORD
        value: ${AUTHENTIK_BOOTSTRAP_PASSWORD}

      # URLs
      - name: AUTHENTIK_EXTERNAL_HOST
        value: ${AUTHENTIK_EXTERNAL_HOST}

      # Disable Redis (Authentik 2025.10+)
      - name: AUTHENTIK_REDIS__HOST
        value: ""

      # Logging
      - name: AUTHENTIK_LOG_LEVEL
        value: info

    # Resource allocation
    resources:
      cpu: 0.5
      memory: 1Gi

    # Dependencies
    dependsOn:
      - authentik-db

    # Restart policy
    restart: unless-stopped

  # ===========================================================================
  # AUTHENTIK WORKER - Background Tasks
  # ===========================================================================
  authentik-worker:
    build:
      context: ./authentik-worker
      dockerfile: Dockerfile

    # Environment variables (same as server)
    environment:
      - name: AUTHENTIK_POSTGRESQL__HOST
        value: authentik-db.railway.internal
      - name: AUTHENTIK_POSTGRESQL__NAME
        value: ${AUTHENTIK_POSTGRESQL__NAME}
      - name: AUTHENTIK_POSTGRESQL__USER
        value: ${AUTHENTIK_POSTGRESQL__USER}
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        value: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      - name: AUTHENTIK_SECRET_KEY
        value: ${AUTHENTIK_SECRET_KEY}
      - name: AUTHENTIK_EXTERNAL_HOST
        value: ${AUTHENTIK_EXTERNAL_HOST}
      - name: AUTHENTIK_REDIS__HOST
        value: ""
      - name: AUTHENTIK_LOG_LEVEL
        value: info

    # Resource allocation (lighter than server)
    resources:
      cpu: 0.25
      memory: 512Mi

    # Dependencies
    dependsOn:
      - authentik-server

    # Restart policy
    restart: unless-stopped

  # ===========================================================================
  # AUTHENTIK PROXY - Caddy Reverse Proxy with Forward Auth
  # ===========================================================================
  authentik-proxy:
    build:
      context: ./authentik-proxy
      dockerfile: Dockerfile

    # Port configuration (public-facing)
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
        description: "HTTP Proxy Port"

    # Health check
    healthcheck:
      path: /health
      port: 8080
      interval: 30s
      timeout: 5s
      startPeriod: 30s
      retries: 3

    # Environment variables
    environment:
      - name: PORT
        value: "8080"
      - name: SIGNAL_LINK_TOKEN
        value: ${SIGNAL_LINK_TOKEN}
      - name: AUTHENTIK_URL
        value: http://authentik-server:9000

    # Resource allocation (lightweight)
    resources:
      cpu: 0.25
      memory: 256Mi

    # Dependencies
    dependsOn:
      - authentik-server
      - moltbot

    # Restart policy
    restart: unless-stopped

# =============================================================================
# VOLUME CONFIGURATION
# =============================================================================

volumes:
  # Persistent storage for moltbot data
  clawdbot-data:
    size: 10Gi
    description: "OpenClaw agent state, workspaces, and session data"

  # Persistent storage for Neo4j data
  neo4j-data:
    size: 20Gi
    description: "Neo4j graph database storage"

  # Persistent storage for Neo4j logs
  neo4j-logs:
    size: 5Gi
    description: "Neo4j log files"

  # Persistent storage for Authentik PostgreSQL
  authentik-db-data:
    size: 10Gi
    description: "Authentik PostgreSQL database storage"

# =============================================================================
# DEPLOYMENT CONFIGURATION
# =============================================================================

deploy:
  # Number of replicas for each service
  replicas:
    moltbot: 1
    skill-sync-service: 1
    neo4j: 1
    authentik-db: 1
    authentik-server: 1
    authentik-worker: 1
    authentik-proxy: 1

  # Deployment strategy
  strategy: rolling

  # Health check grace period
  healthcheckGracePeriod: 180s

# =============================================================================
# NOTES FOR RAILWAY DEPLOYMENT
# =============================================================================
#
# 1. Environment Variables to Set in Railway Dashboard:
#    - OPENCLAW_GATEWAY_TOKEN: Secure token for gateway authentication
#    - NEO4J_PASSWORD: Strong password for Neo4j (overrides the default)
#
# 2. Authentik Environment Variables (REQUIRED):
#    - AUTHENTIK_SECRET_KEY: 50+ character random string (generate with: openssl rand -hex 32)
#    - AUTHENTIK_BOOTSTRAP_PASSWORD: Initial admin password (change after first login)
#    - AUTHENTIK_EXTERNAL_HOST: https://kublai.kurult.ai
#    - AUTHENTIK_POSTGRESQL__USER: postgres (or custom username)
#    - AUTHENTIK_POSTGRESQL__PASSWORD: Strong database password
#    - AUTHENTIK_POSTGRESQL__NAME: authentik
#    - SIGNAL_LINK_TOKEN: Random token for SSE endpoint (generate with: openssl rand -hex 32)
#
# 3. Skill Sync Service Environment Variables (REQUIRED):
#    - GITHUB_TOKEN: GitHub personal access token with repo access (for private repos)
#    - GITHUB_WEBHOOK_SECRET: Secret for webhook validation (generate with: openssl rand -hex 32)
#
# 4. Health Check Endpoints:
#    - moltbot: http://<service>:18789/health
#    - skill-sync-service: http://<service>:3000/health
#    - neo4j: http://<service>:7474/
#    - authentik-server: http://<service>:9000/-/health/ready/
#
# 5. Authentik Admin Access:
#    - After deployment, access Authentik at: https://kublai.kurult.ai/if/admin/
#    - Login with: akadmin / AUTHENTIK_BOOTSTRAP_PASSWORD
#    - Run bootstrap script: python authentik-proxy/bootstrap_authentik.py
#
# 6. Volume Persistence:
#    - Data persists across deployments
#    - Back up important data regularly (see scripts/backup-authentik-db.sh)
#    - clawdbot-data volume is SHARED between moltbot and skill-sync-service
#      - moltbot reads: /data/skills for hot-reloadable skills
#      - skill-sync-service writes: /data/skills from GitHub
#
# 7. Service Dependencies:
#    - authentik-db starts first
#    - authentik-server waits for authentik-db
#    - authentik-worker waits for authentik-server
#    - authentik-proxy waits for authentik-server and moltbot
#    - skill-sync-service waits for neo4j (for audit logging)
#    - moltbot waits for neo4j
#
# 8. Security:
#    - Change default passwords before production use
#    - Consider enabling SSL/TLS for Neo4j connections
#    - Use Railway's private networking for service-to-service communication
#    - Keep AUTHENTIK_SECRET_KEY secure - it encrypts sensitive data
