# Railway Deployment Configuration for OpenClaw Multi-Agent System
# This file configures the moltbot gateway service, Neo4j database, and Authentik
# Reference: moltbot.json shows gateway runs on port 18789

# =============================================================================
# SERVICES CONFIGURATION
# =============================================================================

services:
  # ===========================================================================
  # MOLTBOT SERVICE - Main OpenClaw Gateway
  # ===========================================================================
  moltbot:
    build:
      context: .
      dockerfile: Dockerfile

    # Port configuration (gateway runs on 18789 per moltbot.json)
    ports:
      - port: 18789
        targetPort: 18789
        protocol: TCP
      - port: 8080
        targetPort: 8080
        protocol: TCP

    # Health check endpoint
    healthcheck:
      path: /health
      port: 18789
      interval: 30s
      timeout: 10s
      startPeriod: 5s
      retries: 3

    # Environment variables from .env file
    envFile: .env

    # Additional environment variables
    environment:
      # OpenClaw Gateway Configuration
      - name: OPENCLAW_GATEWAY_PORT
        value: "18789"
      - name: OPENCLAW_CONTROL_UI_ENABLED
        value: "true"

      # Neo4j Connection
      - name: NEO4J_URI
        value: "bolt://neo4j:7687"
      - name: NEO4J_USER
        value: "neo4j"
      # NEO4J_PASSWORD should be set via Railway dashboard or .env

      # Data directories
      - name: CLAWDBOT_STATE_DIR
        value: "/data/.clawdbot"
      - name: CLAWDBOT_WORKSPACE_DIR
        value: "/data/workspace"

      # Python configuration
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: PYTHONDONTWRITEBYTECODE
        value: "1"

    # Resource allocation (adjust based on needs)
    resources:
      cpu: 1
      memory: 2Gi

    # Volume mounts for persistent data
    volumes:
      - name: clawdbot-data
        mountPath: /data

    # Restart policy
    restart: unless-stopped

    # Dependencies - ensure Neo4j starts first
    dependsOn:
      - neo4j

  # ===========================================================================
  # NEO4J SERVICE - Graph Database
  # ===========================================================================
  neo4j:
    image: neo4j:5-community

    # Port configuration
    ports:
      - port: 7474
        targetPort: 7474
        protocol: TCP
        description: "Neo4j HTTP Browser"
      - port: 7687
        targetPort: 7687
        protocol: TCP
        description: "Neo4j Bolt Protocol"

    # Health check using Neo4j's built-in health endpoint
    healthcheck:
      path: /db/manage/server/jmx/domain/org.neo4j/instance%3Dkernel%230%2Cname%3DDiagnostics
      port: 7474
      interval: 30s
      timeout: 10s
      startPeriod: 60s
      retries: 5

    # Environment variables for Neo4j configuration
    environment:
      # Authentication (format: neo4j/password)
      # IMPORTANT: Set NEO4J_USER and NEO4J_PASSWORD via Railway dashboard
      - name: NEO4J_AUTH
        value: ${NEO4J_USER}/${NEO4J_PASSWORD}

      # Plugins (APOC and GDS - Graph Data Science)
      - name: NEO4J_PLUGINS
        value: '["apoc", "gds"]'

      # Memory settings (adjust based on Railway plan)
      - name: NEO4J_dbms_memory_heap_initial__size
        value: "512m"
      - name: NEO4J_dbms_memory_heap_max__size
        value: "1G"
      - name: NEO4J_dbms_memory_pagecache_size
        value: "512m"

      # Accept license for enterprise features (if using enterprise edition)
      # - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
      #   value: "yes"

      # Enable remote connections
      - name: NEO4J_dbms_default__listen__address
        value: "0.0.0.0"

      # Logging configuration
      - name: NEO4J_dbms_logs_debug_level
        value: "INFO"

    # Resource allocation
    resources:
      cpu: 1
      memory: 2Gi

    # Volume mounts for data persistence
    volumes:
      - name: neo4j-data
        mountPath: /data
      - name: neo4j-logs
        mountPath: /logs

    # Restart policy
    restart: unless-stopped

  # ===========================================================================
  # AUTHENTIK DATABASE - PostgreSQL for Authentik
  # ===========================================================================
  authentik-db:
    image: postgres:15-alpine

    # Health check for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTHENTIK_POSTGRESQL__USER} -d ${AUTHENTIK_POSTGRESQL__NAME}"]
      interval: 10s
      timeout: 5s
      startPeriod: 30s
      retries: 5

    # Environment variables
    environment:
      - name: POSTGRES_USER
        value: ${AUTHENTIK_POSTGRESQL__USER}
      - name: POSTGRES_PASSWORD
        value: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      - name: POSTGRES_DB
        value: ${AUTHENTIK_POSTGRESQL__NAME}

    # Resource allocation
    resources:
      cpu: 0.5
      memory: 512Mi

    # Volume mounts for data persistence
    volumes:
      - name: authentik-db-data
        mountPath: /var/lib/postgresql/data

    # Restart policy
    restart: unless-stopped

  # ===========================================================================
  # AUTHENTIK SERVER - Identity Provider
  # ===========================================================================
  authentik-server:
    build:
      context: ./authentik-server
      dockerfile: Dockerfile

    # Port configuration
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        description: "Authentik HTTP API"
      - port: 9443
        targetPort: 9443
        protocol: TCP
        description: "Authentik HTTPS API"

    # Health check
    healthcheck:
      path: /-/health/ready/
      port: 9000
      interval: 30s
      timeout: 10s
      startPeriod: 120s
      retries: 5

    # Environment variables
    environment:
      # Database connection
      - name: AUTHENTIK_POSTGRESQL__HOST
        value: authentik-db.railway.internal
      - name: AUTHENTIK_POSTGRESQL__NAME
        value: ${AUTHENTIK_POSTGRESQL__NAME}
      - name: AUTHENTIK_POSTGRESQL__USER
        value: ${AUTHENTIK_POSTGRESQL__USER}
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        value: ${AUTHENTIK_POSTGRESQL__PASSWORD}

      # Security
      - name: AUTHENTIK_SECRET_KEY
        value: ${AUTHENTIK_SECRET_KEY}
      - name: AUTHENTIK_BOOTSTRAP_PASSWORD
        value: ${AUTHENTIK_BOOTSTRAP_PASSWORD}

      # URLs
      - name: AUTHENTIK_EXTERNAL_HOST
        value: ${AUTHENTIK_EXTERNAL_HOST}

      # Disable Redis (Authentik 2025.10+)
      - name: AUTHENTIK_REDIS__HOST
        value: ""

      # Logging
      - name: AUTHENTIK_LOG_LEVEL
        value: info

    # Resource allocation
    resources:
      cpu: 0.5
      memory: 1Gi

    # Dependencies
    dependsOn:
      - authentik-db

    # Restart policy
    restart: unless-stopped

  # ===========================================================================
  # AUTHENTIK WORKER - Background Tasks
  # ===========================================================================
  authentik-worker:
    build:
      context: ./authentik-worker
      dockerfile: Dockerfile

    # Environment variables (same as server)
    environment:
      - name: AUTHENTIK_POSTGRESQL__HOST
        value: authentik-db.railway.internal
      - name: AUTHENTIK_POSTGRESQL__NAME
        value: ${AUTHENTIK_POSTGRESQL__NAME}
      - name: AUTHENTIK_POSTGRESQL__USER
        value: ${AUTHENTIK_POSTGRESQL__USER}
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        value: ${AUTHENTIK_POSTGRESQL__PASSWORD}
      - name: AUTHENTIK_SECRET_KEY
        value: ${AUTHENTIK_SECRET_KEY}
      - name: AUTHENTIK_EXTERNAL_HOST
        value: ${AUTHENTIK_EXTERNAL_HOST}
      - name: AUTHENTIK_REDIS__HOST
        value: ""
      - name: AUTHENTIK_LOG_LEVEL
        value: info

    # Resource allocation (lighter than server)
    resources:
      cpu: 0.25
      memory: 512Mi

    # Dependencies
    dependsOn:
      - authentik-server

    # Restart policy
    restart: unless-stopped

  # ===========================================================================
  # AUTHENTIK PROXY - Caddy Reverse Proxy with Forward Auth
  # ===========================================================================
  authentik-proxy:
    build:
      context: ./authentik-proxy
      dockerfile: Dockerfile

    # Port configuration (public-facing)
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
        description: "HTTP Proxy Port"

    # Health check
    healthcheck:
      path: /health
      port: 8080
      interval: 30s
      timeout: 5s
      startPeriod: 30s
      retries: 3

    # Environment variables
    environment:
      - name: PORT
        value: "8080"
      - name: SIGNAL_LINK_TOKEN
        value: ${SIGNAL_LINK_TOKEN}
      - name: AUTHENTIK_URL
        value: http://authentik-server:9000

    # Resource allocation (lightweight)
    resources:
      cpu: 0.25
      memory: 256Mi

    # Dependencies
    dependsOn:
      - authentik-server
      - moltbot

    # Restart policy
    restart: unless-stopped

# =============================================================================
# VOLUME CONFIGURATION
# =============================================================================

volumes:
  # Persistent storage for moltbot data
  clawdbot-data:
    size: 10Gi
    description: "OpenClaw agent state, workspaces, and session data"

  # Persistent storage for Neo4j data
  neo4j-data:
    size: 20Gi
    description: "Neo4j graph database storage"

  # Persistent storage for Neo4j logs
  neo4j-logs:
    size: 5Gi
    description: "Neo4j log files"

  # Persistent storage for Authentik PostgreSQL
  authentik-db-data:
    size: 10Gi
    description: "Authentik PostgreSQL database storage"

# =============================================================================
# DEPLOYMENT CONFIGURATION
# =============================================================================

deploy:
  # Number of replicas for each service
  replicas:
    moltbot: 1
    neo4j: 1
    authentik-db: 1
    authentik-server: 1
    authentik-worker: 1
    authentik-proxy: 1

  # Deployment strategy
  strategy: rolling

  # Health check grace period
  healthcheckGracePeriod: 180s

# =============================================================================
# NOTES FOR RAILWAY DEPLOYMENT
# =============================================================================
#
# 1. Environment Variables to Set in Railway Dashboard:
#    - OPENCLAW_GATEWAY_TOKEN: Secure token for gateway authentication
#    - NEO4J_PASSWORD: Strong password for Neo4j (overrides the default)
#
# 2. Authentik Environment Variables (REQUIRED):
#    - AUTHENTIK_SECRET_KEY: 50+ character random string (generate with: openssl rand -hex 32)
#    - AUTHENTIK_BOOTSTRAP_PASSWORD: Initial admin password (change after first login)
#    - AUTHENTIK_EXTERNAL_HOST: https://kublai.kurult.ai
#    - AUTHENTIK_POSTGRESQL__USER: postgres (or custom username)
#    - AUTHENTIK_POSTGRESQL__PASSWORD: Strong database password
#    - AUTHENTIK_POSTGRESQL__NAME: authentik
#    - SIGNAL_LINK_TOKEN: Random token for SSE endpoint (generate with: openssl rand -hex 32)
#
# 3. Health Check Endpoints:
#    - moltbot: http://<service>:18789/health
#    - neo4j: http://<service>:7474/db/manage/server/jmx/...
#    - authentik-server: http://<service>:9000/-/health/ready/
#
# 4. Authentik Admin Access:
#    - After deployment, access Authentik at: https://kublai.kurult.ai/if/admin/
#    - Login with: akadmin / AUTHENTIK_BOOTSTRAP_PASSWORD
#    - Run bootstrap script: python authentik-proxy/bootstrap_authentik.py
#
# 5. Volume Persistence:
#    - Data persists across deployments
#    - Back up important data regularly (see scripts/backup-authentik-db.sh)
#
# 6. Service Dependencies:
#    - authentik-db starts first
#    - authentik-server waits for authentik-db
#    - authentik-worker waits for authentik-server
#    - authentik-proxy waits for authentik-server and moltbot
#
# 7. Security:
#    - Change default passwords before production use
#    - Consider enabling SSL/TLS for Neo4j connections
#    - Use Railway's private networking for service-to-service communication
#    - Keep AUTHENTIK_SECRET_KEY secure - it encrypts sensitive data
