#!/usr/bin/env python3
"""
Kurultai System Health Dashboard
A real-time, terminal-based system monitor for macOS using curses and psutil.

Generated by: Temüjin (Developer Agent) via Gemini CLI
Model: gemini-3.1-pro-preview
Date: 2026-02-25
"""
from __future__ import annotations

import curses
import psutil
import time
import sys

def bytes2human(n):
    """Converts bytes to a human-readable string format."""
    symbols = ('K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y')
    prefix = {}
    for i, s in enumerate(symbols):
        prefix[s] = 1 << (i + 1) * 10
    for s in reversed(symbols):
        if n >= prefix[s]:
            value = float(n) / prefix[s]
            return '%.1f%s' % (value, s)
    return "%sB" % n

def get_color(percentage):
    """Returns the appropriate color pair based on usage percentage."""
    if percentage > 85:
        return curses.color_pair(3) | curses.A_BOLD # Red for critical
    elif percentage > 65:
        return curses.color_pair(2) | curses.A_BOLD # Yellow for warning
    else:
        return curses.color_pair(1)                 # Green for normal

def draw_progress_bar(window, y, x, width, percentage, label, color_attr):
    """Draws a formatted progress bar."""
    bar_width = max(10, width - len(label) - 15)
    filled = int((percentage / 100) * bar_width)
    bar = '[' + '#' * filled + '-' * (bar_width - filled) + ']'
    window.addstr(y, x, f"{label:<8}: {bar} {percentage:>5.1f}%", color_attr)

def main(stdscr):
    # Terminal Initialization
    curses.curs_set(0)  # Hide the cursor
    stdscr.nodelay(1)   # Make getch() non-blocking
    stdscr.timeout(1000) # Refresh every 1000 ms (1 second)

    # Setup Colors
    curses.start_color()
    curses.use_default_colors()
    curses.init_pair(1, curses.COLOR_GREEN, -1)   # Normal
    curses.init_pair(2, curses.COLOR_YELLOW, -1)  # Warning
    curses.init_pair(3, curses.COLOR_RED, -1)     # Critical
    curses.init_pair(4, curses.COLOR_CYAN, -1)    # Header

    # Main Loop
    while True:
        stdscr.clear()
        height, width = stdscr.getmaxyx()

        # Header
        stdscr.addstr(0, 0, "=" * (width - 1), curses.color_pair(4))
        stdscr.addstr(1, 2, "KURULTAI SYSTEM HEALTH DASHBOARD", curses.color_pair(4) | curses.A_BOLD)
        stdscr.addstr(2, 2, f"Generated by Temüjin via Gemini CLI | {time.strftime('%Y-%m-%d %H:%M:%S')}")
        stdscr.addstr(3, 0, "=" * (width - 1), curses.color_pair(4))

        # CPU Usage
        cpu_percent = psutil.cpu_percent(interval=0.1)
        cpu_color = get_color(cpu_percent)
        draw_progress_bar(stdscr, 5, 2, width - 4, cpu_percent, "CPU", cpu_color)

        # Memory Usage
        memory = psutil.virtual_memory()
        mem_color = get_color(memory.percent)
        draw_progress_bar(stdscr, 7, 2, width - 4, memory.percent, "Memory", mem_color)
        stdscr.addstr(8, 4, f"Used: {bytes2human(memory.used)} / Total: {bytes2human(memory.total)}")

        # Disk Usage
        disk = psutil.disk_usage('/')
        disk_percent = disk.percent
        disk_color = get_color(disk_percent)
        draw_progress_bar(stdscr, 10, 2, width - 4, disk_percent, "Disk", disk_color)
        stdscr.addstr(11, 4, f"Free: {bytes2human(disk.free)} / Total: {bytes2human(disk.total)}")

        # Network I/O
        net_io = psutil.net_io_counters()
        stdscr.addstr(13, 2, "Network I/O:", curses.A_BOLD)
        stdscr.addstr(14, 4, f"Sent: {bytes2human(net_io.bytes_sent)} | Received: {bytes2human(net_io.bytes_recv)}")

        # Running Processes
        stdscr.addstr(16, 2, "Top Processes:", curses.A_BOLD)
        processes = sorted(
            psutil.process_iter(['pid', 'name', 'cpu_percent']),
            key=lambda p: p.info['cpu_percent'] or 0,
            reverse=True
        )[:5]
        
        for i, proc in enumerate(processes):
            try:
                stdscr.addstr(17 + i, 4, f"{proc.info['pid']:>6} {proc.info['name'][:20]:<20} {proc.info['cpu_percent'] or 0:>5.1f}%")
            except:
                pass

        # Footer
        stdscr.addstr(height - 2, 0, "=" * (width - 1), curses.color_pair(4))
        stdscr.addstr(height - 1, 2, "Press 'q' to quit | Press any key to refresh", curses.A_DIM)

        stdscr.refresh()

        # Check for quit
        key = stdscr.getch()
        if key == ord('q'):
            break
        elif key == ord('r'):
            continue

if __name__ == "__main__":
    print("Kurultai System Health Dashboard")
    print("=================================")
    print("Generated by: Temüjin (Developer Agent)")
    print("Via: Gemini CLI (gemini-3.1-pro-preview)")
    print()
    print("Starting dashboard...")
    print("Note: Requires 'psutil' library")
    print("      Install: pip install psutil")
    print()
    
    try:
        curses.wrapper(main)
    except KeyboardInterrupt:
        print("\nDashboard stopped.")
    except Exception as e:
        print(f"\nError: {e}")
        print("Make sure your terminal supports curses and you have psutil installed.")
