# skill-sync-service Railway Configuration
# This service syncs skills from GitHub to a shared /data/skills directory

services:
  # ===========================================================================
  # SKILL SYNC SERVICE - GitHub skill synchronization worker
  # ===========================================================================
  skill-sync-service:
    build:
      context: ./skill-sync-service
      dockerfile: Dockerfile

    # Health check endpoint
    healthcheck:
      path: /health
      port: 3000
      interval: 30s
      timeout: 10s
      startPeriod: 30s
      retries: 5

    # Environment variables
    envFile: .env

    environment:
      # Service Configuration
      - name: PORT
        value: "3000"
      - name: NODE_ENV
        value: production
      - name: LOG_LEVEL
        value: info

      # Skill Storage - shared with moltbot via clawdbot-data volume
      - name: SKILLS_DIR
        value: /data/skills
      - name: BACKUP_DIR
        value: /data/backups/skills
      - name: MAX_SKILL_SIZE_BYTES
        value: "102400"

      # GitHub Configuration
      - name: GITHUB_OWNER
        value: Danservfinn
      - name: GITHUB_REPO
        value: kurultai-skills
      - name: POLLING_INTERVAL_MIN
        value: "5"
      # GITHUB_WEBHOOK_SECRET and GITHUB_TOKEN set via Railway dashboard

      # Neo4j Audit Logging (shared with other services)
      - name: NEO4J_URI
        value: bolt://neo4j.railway.internal:7687
      - name: NEO4J_USER
        value: neo4j
      # NEO4J_PASSWORD set via Railway dashboard

      # Deployment Lock
      - name: DEPLOYMENT_LOCK_TTL
        value: "300"

    # Resource allocation
    resources:
      cpu: 0.5
      memory: 512Mi

    # CRITICAL: Shared volume with moltbot - same name and mount path
    # This allows skill-sync-service to write to /data/skills and moltbot to read
    volumes:
      - name: clawdbot-data
        mountPath: /data

    # Restart policy
    restart: unless-stopped

    # Dependencies - ensure moltbot is ready (optional, service runs independently)
    # dependsOn:
    #   - moltbot
