#!/usr/bin/env python3
"""
Completion Gate Audit - Pre-completion quality gate for task completion

Analyzes task completion and generates follow-up requirements.
Runs before a task is marked as complete to ensure quality.

Usage:
    from completion_gate_audit import completion_gate_audit, AuditResult

    result = completion_gate_audit(task_file, agent)
    if not result.can_complete:
        # Create follow-up tasks
        create_followup_tasks(result, task_metadata)
"""

import os
import re
import json
import uuid
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass, field, asdict
from typing import Optional, List, Dict, Any

# Add scripts dir to path for imports
sys_path_insert = os.path.dirname(os.path.abspath(__file__))
if sys_path_insert not in os.sys.path:
    os.sys.path.insert(0, sys_path_insert)

from kurultai_paths import AGENTS_DIR, TASK_LEDGER
from kurultai_ledger import append_ledger

# Gate configuration
GATE_THRESHOLD_PERCENT = 90  # Minimum completion % to pass gate
MAX_FOLLOWUPS_PER_AUDIT = 5  # Limit follow-ups per audit cycle

# Audit log directory
AUDIT_LOG_DIR = Path(AGENTS_DIR) / "main" / "logs" / "gate-audits"


@dataclass
class FollowupTask:
    """A follow-up task generated by the gate audit."""
    title: str
    agent: str
    priority: str
    reason: str


@dataclass
class AuditResult:
    """Result of a completion gate audit."""
    original_task: str
    completion_percentage: int
    can_complete: bool
    missing_components: List[str] = field(default_factory=list)
    quality_issues: List[str] = field(default_factory=list)
    required_followups: List[Dict[str, str]] = field(default_factory=list)
    optional_improvements: List[Dict[str, str]] = field(default_factory=list)
    blockers: List[str] = field(default_factory=list)
    gate_cycle: int = 0
    audit_timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    audit_version: str = "1.0"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


def extract_yaml_frontmatter(content: str) -> Dict[str, Any]:
    """Extract YAML frontmatter from task content."""
    metadata = {}
    if not content.startswith('---'):
        return metadata

    # Find the closing ---
    lines = content.split('\n')
    in_frontmatter = False
    frontmatter_lines = []

    for i, line in enumerate(lines):
        if i == 0 and line.strip() == '---':
            in_frontmatter = True
            continue
        if in_frontmatter and line.strip() == '---':
            break
        if in_frontmatter:
            frontmatter_lines.append(line)

    # Parse simple YAML key-value pairs
    for line in frontmatter_lines:
        if ':' in line:
            key, _, value = line.partition(':')
            metadata[key.strip()] = value.strip().strip('"\'').strip()

    return metadata


def extract_body_after_frontmatter(content: str) -> str:
    """Extract the body content after YAML frontmatter."""
    if not content.startswith('---'):
        return content

    # Find the closing ---
    lines = content.split('\n')
    found_close = False
    body_start = 0

    for i, line in enumerate(lines):
        if i > 0 and line.strip() == '---':
            found_close = True
            body_start = i + 1
            break

    if not found_close:
        return content

    return '\n'.join(lines[body_start:])


def extract_execution_output(content: str) -> str:
    """Extract execution output section from task content.

    SECURITY: Uses rsplit() to find the LAST occurrence of the marker,
    which is always the system-controlled marker added by the execution system.
    This prevents injection attacks where task descriptions contain the marker.
    """
    marker = '## Execution Output'
    if marker not in content:
        return ""

    parts = content.rsplit(marker, 1)
    if len(parts) < 2:
        return ""

    return parts[1].strip()


def fallback_template_audit(task_content: Dict[str, Any], execution_output: str) -> Dict[str, Any]:
    """
    Fallback audit when LLM is unavailable.
    Uses heuristic template matching.
    """
    missing = []
    improvements = []
    task_title = task_content.get('title', '')
    task_body = task_content.get('body', '')

    # Pattern 1: TODO/FIXME in output
    if re.search(r'\b(TODO|FIXME|XXX|HACK)\b', execution_output, re.I):
        missing.append("Incomplete items marked TODO/FIXME in code")

    # Pattern 2: Test required but not mentioned
    if 'test' in task_title.lower() or 'test' in task_body.lower():
        if 'test' not in execution_output.lower():
            missing.append("Tests not written")

    # Pattern 3: Error handling not mentioned for endpoints/APIs
    if 'endpoint' in execution_output.lower() or 'api' in execution_output.lower():
        if 'error' not in execution_output.lower() and 'catch' not in execution_output.lower():
            improvements.append("Add error handling")

    # Pattern 4: No documentation mentioned
    if 'implement' in task_title.lower() or 'add' in task_title.lower():
        if 'doc' not in execution_output.lower():
            improvements.append("Add documentation")

    # Pattern 5: Very short output
    output_lines = [l for l in execution_output.split('\n') if l.strip() and not l.strip().startswith('**')]
    if len(output_lines) < 10:
        missing.append("Insufficient execution output")

    can_complete = len(missing) == 0 and len(improvements) == 0
    completion_percentage = 100 if can_complete else max(50, 100 - len(missing) * 15 - len(improvements) * 5)

    return {
        "completion_percentage": completion_percentage,
        "can_complete": can_complete,
        "missing_components": missing,
        "quality_issues": [],
        "required_followups": [
            {"title": m, "agent": task_content.get('agent', 'temujin'), "priority": "high", "reason": "Auto-detected"}
            for m in missing
        ],
        "optional_improvements": [
            {"title": i, "agent": task_content.get('agent', 'temujin'), "priority": "normal", "reason": "Auto-suggested"}
            for i in improvements
        ],
        "blockers": []
    }


def call_llm_for_audit(task_id: str, task_title: str, task_body: str, execution_output: str) -> Optional[Dict[str, Any]]:
    """
    Call LLM for audit analysis.

    Returns parsed JSON result or None if unavailable.
    """
    try:
        import openai
    except ImportError:
        return None

    # Check for API credentials
    api_key = os.getenv("OPENAI_API_KEY") or os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    # Limit content length
    task_body_limited = task_body[:2000] if task_body else ""
    exec_output_limited = execution_output[:5000] if execution_output else ""

    audit_prompt = f"""You are a Completion Auditor. Analyze if this task is truly complete.

TASK ID: {task_id}
TASK TITLE: {task_title}

ORIGINAL REQUIREMENTS:
{task_body_limited}

EXECUTION OUTPUT (what was delivered):
{exec_output_limited}

Audit the task completion:

1. REQUIREMENTS_COVERAGE: What % of requirements were met? (0-100)
2. MISSING_COMPONENTS: List specific missing items
3. QUALITY_ISSUES: List any quality problems (tests missing, docs incomplete, etc.)
4. DEPENDENCIES_NEEDED: List dependencies that should be created
5. IMPROVEMENTS_SUGGESTED: Optional improvements for better quality

Output ONLY valid JSON (no markdown, no code fence):
{{
  "completion_percentage": 85,
  "can_complete": false,
  "missing_components": ["Credit pack display not fixed", "Webhook handler missing"],
  "quality_issues": ["No tests written", "Error handling incomplete"],
  "required_followups": [
    {{"title": "Fix credit pack display", "agent": "temujin", "priority": "high", "reason": "UX bug"}},
    {{"title": "Add webhook handler", "agent": "temujin", "priority": "high", "reason": "Required for Stripe"}}
  ],
  "optional_improvements": [
    {{"title": "Add analytics", "agent": "mongke", "priority": "normal", "reason": "Track usage"}}
  ],
  "blockers": ["Stripe credentials needed from human"]
}}"""

    try:
        client = openai.OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model="gpt-4o-mini",  # Fast, cheap for audit
            messages=[{"role": "user", "content": audit_prompt}],
            max_tokens=1000,
            temperature=0.3
        )

        result_text = response.choices[0].message.content.strip()

        # Remove potential markdown code fences
        if result_text.startswith('```'):
            result_text = re.sub(r'^```(?:json)?\s*', '', result_text)
            result_text = re.sub(r'\s*```$', '', result_text)

        return json.loads(result_text)
    except Exception as e:
        print(f"[completion_gate] LLM audit failed: {e}")
        return None


def completion_gate_audit(task_file: str, agent: str) -> AuditResult:
    """
    Analyze task completion and generate follow-up requirements.

    Args:
        task_file: Path to the task file (.executing.md)
        agent: Agent who executed the task

    Returns: AuditResult with completion status and follow-up tasks
    """
    task_path = Path(task_file)
    if not task_path.exists():
        return AuditResult(
            original_task="unknown",
            audit_timestamp=datetime.now().isoformat(),
            audit_version="1.0",
            completion_percentage=0,
            can_complete=False,
            blockers=["Task file not found"]
        )

    # Read task content
    try:
        with open(task_path, 'r') as f:
            content = f.read()
    except Exception as e:
        return AuditResult(
            original_task="unknown",
            audit_timestamp=datetime.now().isoformat(),
            audit_version="1.0",
            completion_percentage=0,
            can_complete=False,
            blockers=[f"Failed to read task file: {e}"]
        )

    # Parse frontmatter and body
    metadata = extract_yaml_frontmatter(content)
    task_id = metadata.get('task_id', task_path.stem)
    task_title = metadata.get('title', task_path.stem)
    task_body = extract_body_after_frontmatter(content)
    execution_output = extract_execution_output(content)

    # Try LLM audit first, fall back to template
    llm_result = call_llm_for_audit(task_id, task_title, task_body, execution_output)

    if llm_result:
        audit_data = llm_result
    else:
        # Fallback to template-based audit
        audit_data = fallback_template_audit(
            {'agent': agent, 'title': task_title, 'body': task_body},
            execution_output
        )

    # Enforce gate rules
    # Rule: cannot complete if completion_percentage < 90 AND required_followups > 0
    if audit_data["completion_percentage"] < GATE_THRESHOLD_PERCENT and audit_data.get("required_followups"):
        audit_data["can_complete"] = False

    # Rule: cannot complete if blockers exist
    if audit_data.get("blockers"):
        audit_data["can_complete"] = False

    # Rule: 100% completion with no issues auto-passes
    if audit_data["completion_percentage"] >= 100:
        audit_data["can_complete"] = True
        audit_data["required_followups"] = []

    # Validate and fix follow-up target agents
    valid_agents = {'kublai', 'temujin', 'mongke', 'chagatai', 'jochi', 'ogedei', 'tolui'}
    for followup in audit_data.get("required_followups", []) + audit_data.get("optional_improvements", []):
        if followup.get("agent") not in valid_agents:
            followup["agent"] = agent  # Default to current agent

    # Limit number of follow-ups
    if len(audit_data.get("required_followups", [])) > MAX_FOLLOWUPS_PER_AUDIT:
        audit_data["required_followups"] = audit_data["required_followups"][:MAX_FOLLOWUPS_PER_AUDIT]

    # Build result
    result = AuditResult(
        original_task=task_id,
        audit_timestamp=datetime.now().isoformat(),
        audit_version="1.0",
        completion_percentage=audit_data["completion_percentage"],
        can_complete=audit_data["can_complete"],
        missing_components=audit_data.get("missing_components", []),
        quality_issues=audit_data.get("quality_issues", []),
        required_followups=audit_data.get("required_followups", []),
        optional_improvements=audit_data.get("optional_improvements", []),
        blockers=audit_data.get("blockers", []),
        gate_cycle=int(metadata.get('gate_cycle', 0))
    )

    # Save audit log
    save_audit_log(result, task_path)

    return result


def save_audit_log(result: AuditResult, task_path: Path) -> str:
    """Save audit result to JSON log file."""
    AUDIT_LOG_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    log_file = AUDIT_LOG_DIR / f"{result.original_task}-{timestamp}.json"

    with open(log_file, 'w') as f:
        json.dump(result.to_dict(), f, indent=2)

    return str(log_file)


def create_followup_tasks(audit_result: AuditResult, original_task: Dict[str, Any], original_file: str) -> List[str]:
    """
    Create follow-up tasks from audit results.

    Args:
        audit_result: The audit result with follow-up specifications
        original_task: Metadata from the original task
        original_file: Path to the original task file

    Returns: List of created task file paths
    """
    created_tasks = []
    original_task_id = audit_result.original_task
    original_agent = original_task.get('agent', 'temujin')
    audit_ref = save_audit_log(audit_result, Path(original_file))

    for i, followup in enumerate(audit_result.required_followups):
        task_id = f"gate-{original_task_id[:8]}-{uuid.uuid4().hex[:8]}"
        priority = followup.get("priority", "high")
        target_agent = followup.get("agent", original_agent)

        # Build task frontmatter
        depth = original_task.get('depth', 0) + 1

        frontmatter = f"""---
agent: {target_agent}
priority: {priority}
created: {datetime.now().isoformat()}
source: completion-gate
depth: {depth}
task_id: {task_id}
parent_task: {original_task_id}
completion_gate: true
gate_audit_ref: {audit_ref}
gate_required: true
bucket: TODAY
domain: implementation
timeout: 3600
skill_hint: null
---

"""

        # Build task body
        body = f"""# Task: {followup['title']}

This is a **completion gate follow-up task** for parent: `{original_task_id}`

## Parent Context

The parent task identified that the following item is incomplete or missing:
- **Issue:** {followup['reason']}
- **Original completion:** {audit_result.completion_percentage}%

This follow-up must be completed before the parent task can be marked as fully complete.

## What to Do

1. Analyze the parent task to understand context
2. Implement the required fix or improvement
3. Test your changes
4. Update any relevant documentation

## Audit Reason

> {followup['reason']}

## Success Criteria

- [ ] Fix/improvement implemented and tested
- [ ] No regressions introduced
- [ ] Documentation updated if applicable

---
_Generated by completion-gate-audit at {datetime.now().isoformat()}_
"""

        # Write task file
        task_dir = Path(AGENTS_DIR) / target_agent / "tasks"
        task_dir.mkdir(parents=True, exist_ok=True)
        task_path = task_dir / f"{priority}-{task_id}.md"

        with open(task_path, 'w') as f:
            f.write(frontmatter + body)

        created_tasks.append(str(task_path))

        # Track in Neo4j
        try:
            from neo4j_task_tracker import get_tracker
            tracker = get_tracker()
            tracker.create_task_full(
                agent=target_agent,
                title=followup['title'],
                body=body,
                priority=priority,
                source="completion-gate",
                depth=depth,
                parent_id=original_task_id,
                skill_hint=None
            )
            # Add gate-specific properties
            tracker.update_gate_status(task_id, "PENDING", gate_required=True, parent_task=original_task_id)
        except Exception as e:
            print(f"[completion_gate] Neo4j update failed (non-fatal): {e}")

    # Log follow-up creation
    if created_tasks:
        append_ledger({
            "event": "GATE_FOLLOWUPS_CREATED",
            "ts": datetime.now().isoformat(),
            "original_task": original_task_id,
            "followup_count": len(created_tasks),
            "followup_tasks": [os.path.basename(t) for t in created_tasks],
            "completion_percentage": audit_result.completion_percentage
        })

    return created_tasks


def should_run_gate(task_file: str) -> bool:
    """
    Determine if completion gate should run for a task.

    Returns False for:
    - Tasks with completion_gate: false in frontmatter
    - Tasks with completion_gate_optout: true
    - Tasks that are already follow-ups (depth > 2)
    """
    try:
        with open(task_file, 'r') as f:
            content = f.read(2000)

        # Check for opt-out flags
        if re.search(r'^completion_gate:\s*false', content, re.MULTILINE):
            return False
        if re.search(r'^completion_gate_optout:\s*true', content, re.MULTILINE):
            return False

        # Check depth - don't gate follow-ups of follow-ups
        depth_match = re.search(r'^depth:\s*(\d+)', content, re.MULTILINE)
        if depth_match and int(depth_match.group(1)) > 2:
            return False

        return True
    except Exception:
        return True  # Run gate by default


# ==========================================================
# BACKWARD COMPATIBLE ALIASES
# ==========================================================
# These match the interface expected by agent-task-handler.py

def extract_frontmatter(task_path: Path) -> dict:
    """Alias for extract_yaml_frontmatter that accepts Path."""
    try:
        with open(task_path, 'r') as f:
            content = f.read(5000)
        return extract_yaml_frontmatter(content)
    except Exception:
        return {}


def save_audit_result(result: AuditResult, task_id: str = None) -> str:
    """Alias for save_audit_log with compatible signature."""
    task_path = Path(AGENTS_DIR) / "main" / "tasks" / f"{task_id}.md"
    return save_audit_log(result, task_path)


# CLI interface
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Completion Gate Audit")
    parser.add_argument("task_file", help="Path to task file (.executing.md)")
    parser.add_argument("--agent", default="temujin", help="Agent who executed the task")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--no-gate-check", action="store_true", help="Skip should_run_gate check")

    args = parser.parse_args()

    if not args.no_gate_check and not should_run_gate(args.task_file):
        result = {"skipped": True, "reason": "Task opted out of completion gate"}
        print(json.dumps(result) if args.json else "Gate skipped: task opted out")
        exit(0)

    result = completion_gate_audit(args.task_file, args.agent)

    if args.json:
        print(json.dumps(result.to_dict(), indent=2))
    else:
        print(f"Completion Gate Audit: {result.original_task}")
        print(f"  Completion: {result.completion_percentage}%")
        print(f"  Can Complete: {result.can_complete}")
        if result.missing_components:
            print(f"  Missing: {', '.join(result.missing_components)}")
        if result.required_followups:
            print(f"  Follow-ups Required: {len(result.required_followups)}")
            for f in result.required_followups:
                print(f"    - {f['title']} ({f['agent']}, {f['priority']})")
        if result.blockers:
            print(f"  Blockers: {', '.join(result.blockers)}")

    exit(0 if result.can_complete else 1)
