#!/usr/bin/env python3
"""
Agent Meta-Reflection Generator

Generates compact protocol-based reflection prompts (~800 tokens) for all 6
agents using role-specific protocols, WHEN/THEN behavioral rules, and
commitment tracking. Agents submit feedback to Kublai via Neo4j AgentFeedback.

Usage:
    python3 meta_reflection.py --agent temujin --hours 1 --protocol
    python3 meta_reflection.py --all-agents --hours 1 --protocol
"""

import argparse
import json
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(__file__))
from neo4j_task_tracker import get_tracker

from agents_config import AGENTS, AGENT_ROLES, AGENT_MODELS


def get_agent_metrics(agent, hours=1):
    """Get metrics for an agent"""
    tracker = get_tracker()
    
    # Get task data
    task_data = tracker.get_reflection_data(agent, hours)
    
    # Get recent tasks
    try:
        recent_tasks = tracker.get_tasks_by_agent(agent, limit=5)
    except:
        recent_tasks = []
    
    # Get completion rate
    try:
        completion = tracker.get_completion_rate(hours * 24)
    except:
        completion = {}
    
    total = task_data.get('total_tasks', 0) or 0
    completed = task_data.get('completed', 0) or 0
    
    success_rate = f"{100 * completed / total:.1f}%" if total > 0 else "N/A"
    avg_duration = task_data.get('avg_duration')
    
    tracker.close()
    
    return {
        "total_tasks": total,
        "completed": completed,
        "failed": task_data.get('failed', 0) or 0,
        "retries": task_data.get('total_retries', 0) or 0,
        "success_rate": success_rate,
        "avg_duration": f"{avg_duration:.1f}s" if avg_duration else "N/A",
        "recent_tasks": recent_tasks[:5],
        "completion_rate": completion
    }

def generate_protocol_reflection(agent, hours=1, include_heartbeat_review=False):
    """Generate compact protocol-based reflection prompt (Option B).

    Uses role-specific protocols, injects active rules and last commitment
    from prepare_reflection_context.py, reads tock data instead of CLI.
    Target: ~800 tokens per agent (vs ~6400 in legacy mode).
    
    MODEL CHANGE EXCLUSION: Agents are explicitly prohibited from proposing
    model configuration changes. Only humans can change models.
    """
    # Model change exclusion header — agents MUST NOT propose model changes
    model_lock_header = """## ⚠️ MODEL CONFIGURATION LOCK

**CRITICAL:** You are PROHIBITED from proposing, suggesting, or considering any changes to agent model configuration (ANTHROPIC_MODEL, config.json, .claude/settings.json). Model changes are exclusively a human operator decision.

During this reflection:
- DO NOT include model configuration as a potential improvement
- DO NOT create tasks to fix model mismatches
- DO NOT suggest model changes in any deliverable
- If you detect a model mismatch, log it but take NO action

Violating this rule wastes compute and violates human operator authority.

---
"""
    
    try:
        from prepare_reflection_context import generate_context
        context = generate_context(agent, hours=hours)
    except Exception as e:
        context = f"*Protocol context unavailable: {e}*\n"

    # Optionally append heartbeat review
    heartbeat_block = ""
    if include_heartbeat_review:
        try:
            from heartbeat_task_analyzer import generate_review
            heartbeat_block = generate_review(agent, hours=hours)
        except Exception as e:
            heartbeat_block = f"*Heartbeat review unavailable: {e}*\n"

    # Get Neo4j metrics (compact)
    try:
        metrics = get_agent_metrics(agent, hours)
        metrics_block = (
            f"\n## Neo4j Metrics ({hours}h)\n"
            f"- Tasks: {metrics['completed']}/{metrics['total_tasks']} "
            f"({metrics['success_rate']}) | Retries: {metrics['retries']} "
            f"| Avg: {metrics['avg_duration']}\n"
        )
    except Exception:
        metrics_block = ""

    # Assemble compact prompt with model lock header first
    parts = [model_lock_header, context]
    if metrics_block:
        parts.append(metrics_block)
    if heartbeat_block:
        parts.append(f"\n## Infrastructure Pulse\n{heartbeat_block}")
    parts.append(f"\n---\n*Generated by meta_reflection.py (protocol mode) at {datetime.now().strftime('%H:%M')}*")

    return "\n".join(parts)


def submit_feedback(agent, feedback_text, priority="MEDIUM", proposals=None):
    """Submit feedback to Kublai via Neo4j"""
    tracker = get_tracker()
    
    with tracker.driver.session() as session:
        session.run("""
            MERGE (a:Agent {name: $agent})
            CREATE (f:AgentFeedback {
                agent: $agent,
                feedback: $feedback,
                priority: $priority,
                proposals: $proposals,
                submitted: datetime(),
                status: 'pending_review',
                id: $feedback_id
            })
            CREATE (a)-[:SUBMITTED]->(f)
        """,
        agent=agent,
        feedback=feedback_text,
        priority=priority,
        proposals=json.dumps(proposals or []),
        feedback_id=f"{agent}-{int(datetime.now().timestamp())}"
        )
    
    tracker.close()
    print(f"✓ Feedback submitted to Kublai: {agent}")

def get_pending_feedback():
    """Get all pending feedback for Kublai to review"""
    tracker = get_tracker()
    
    with tracker.driver.session() as session:
        result = session.run("""
            MATCH (f:AgentFeedback {status: 'pending_review'})
            RETURN f ORDER BY 
                CASE f.priority 
                    WHEN 'CRITICAL' THEN 1 
                    WHEN 'HIGH' THEN 2 
                    WHEN 'MEDIUM' THEN 3 
                    ELSE 4 
                END,
                f.submitted DESC
        """)
        feedback = [dict(r['f']) for r in result]
    
    tracker.close()
    return feedback

def main():
    parser = argparse.ArgumentParser(description='Generate agent meta-reflections')
    parser.add_argument('--agent', help='Specific agent')
    parser.add_argument('--all-agents', action='store_true', help='Generate for all 6 agents')
    parser.add_argument('--hours', type=int, default=1, help='Hours to look back')
    parser.add_argument('--protocol', action='store_true',
                        help='Use protocol-based reflections (~800 tokens)')
    parser.add_argument('--heartbeat-review', action='store_true', help='Include heartbeat task review')
    parser.add_argument('--submit', action='store_true', help='Submit feedback to Kublai (vs just printing)')
    parser.add_argument('--list-pending', action='store_true', help='List pending feedback for Kublai')

    args = parser.parse_args()

    if args.list_pending:
        feedback = get_pending_feedback()
        print(f"Pending feedback for Kublai: {len(feedback)}")
        for f in feedback:
            print(f"  - [{f.get('priority')}] {f.get('agent')}: {f.get('feedback', '')[:50]}...")
        return

    agents = [args.agent] if args.agent else (list(AGENT_ROLES.keys()) if args.all_agents else [])

    if not agents:
        print("Usage: python3 meta_reflection.py --agent <name> OR --all-agents --protocol")
        sys.exit(1)

    for agent in agents:
        reflection = generate_protocol_reflection(
            agent,
            args.hours,
            include_heartbeat_review=args.heartbeat_review
        )

        if args.submit:
            submit_feedback(
                agent=agent,
                feedback_text=reflection[:500],
                priority="MEDIUM",
                proposals=[]
            )
        else:
            print(f"\n{'='*60}")
            print(f"AGENT: {agent.upper()}")
            print(f"{'='*60}")
            print(reflection)
            print(f"\n{'='*60}\n")

if __name__ == "__main__":
    main()
