#!/usr/bin/env python3
"""
Proposal Generator for Kurultai Consensus Voting System

Each Khan writes their own proposals based on their domain expertise.
Proposals follow a structured format for voting.

Historical Context:
In the authentic Mongolian Kurultai, each Khan brought proposals for
improvements within their domain. Proposals required unanimous consent
from all Khans to be implemented.

Usage:
    python3 proposal_generator.py --agent <agent_name> [--reflection-file <path>]

Output:
    Creates a proposal file in proposals/pending/<agent>-<timestamp>.md
"""

import argparse
import json
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

# Kurultai paths
KURULTAI_ROOT = Path("/Users/kublai/.openclaw/agents/main")
PROPOSALS_DIR = KURULTAI_ROOT / "proposals"
PENDING_DIR = PROPOSALS_DIR / "pending"
MEMORY_DIR = KURULTAI_ROOT / "memory"

# Agent domain definitions
AGENT_DOMAINS = {
    "kublai": {
        "domain": "Routing, coordination, cross-agent orchestration",
        "focus_areas": [
            "Task routing optimization",
            "Cross-agent coordination",
            "Queue balancing",
            "Agent workload management",
            "System-wide improvements"
        ]
    },
    "temujin": {
        "domain": "Development, infrastructure, code, APIs",
        "focus_areas": [
            "Code architecture improvements",
            "Infrastructure optimization",
            "API enhancements",
            "Technical debt reduction",
            "Development workflow improvements"
        ]
    },
    "mongke": {
        "domain": "Research, market analysis, fact-finding",
        "focus_areas": [
            "Research methodology improvements",
            "Market analysis processes",
            "Data sourcing strategies",
            "Knowledge extraction methods",
            "Research quality metrics"
        ]
    },
    "chagatai": {
        "domain": "Documentation, content, marketing",
        "focus_areas": [
            "Documentation improvements",
            "Content quality standards",
            "Marketing strategies",
            "Communication processes",
            "Knowledge base enhancements"
        ]
    },
    "jochi": {
        "domain": "Testing, analysis, security, code review",
        "focus_areas": [
            "Testing coverage improvements",
            "Security enhancements",
            "Code review processes",
            "Quality assurance methods",
            "Anomaly detection"
        ]
    },
    "ogedei": {
        "domain": "Operations, monitoring, incidents, infrastructure",
        "focus_areas": [
            "Monitoring improvements",
            "Incident response processes",
            "Infrastructure automation",
            "Health check enhancements",
            "Operational efficiency"
        ]
    }
}

PROPOSAL_TEMPLATE = '''---
proposal_id: {proposal_id}
agent: {agent}
domain: {domain}
created: {timestamp}
status: pending
voting_deadline: {voting_deadline}
impact: {impact}
effort: {effort}
---

# Proposal: {title}

## Domain
{domain_description}

## Problem Statement
{problem_statement}

## Proposed Solution
{proposed_solution}

## Expected Impact
{expected_impact}

## Implementation Steps
{implementation_steps}

## Resource Requirements
{resource_requirements}

## Risk Assessment
{risk_assessment}

## Success Metrics
{success_metrics}

---
*Generated by {agent} at {timestamp}*
'''


def generate_proposal_id(agent: str) -> str:
    """Generate a unique proposal ID."""
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return f"{agent}-{timestamp}"


def calculate_voting_deadline(hours: int = 1) -> str:
    """Calculate voting deadline (default 1 hour from now)."""
    deadline = datetime.now().replace(minute=0, second=0, microsecond=0)
    # FIX: Use timedelta to handle day boundary correctly
    # (deadline.hour + hours) can exceed 23, causing ValueError
    deadline = deadline + timedelta(hours=hours)
    return deadline.isoformat()


def load_reflection_content(agent: str, reflection_file: Optional[str] = None) -> dict:
    """Load agent's recent reflection content for proposal context."""
    content = {
        "recent_issues": [],
        "recent_improvements": [],
        "suggestions": []
    }

    if reflection_file and os.path.exists(reflection_file):
        try:
            with open(reflection_file, 'r') as f:
                text = f.read()
                # Extract suggestions or improvements from reflection
                if "IMPROVEMENT" in text.upper() or "SUGGESTION" in text.upper():
                    lines = text.split('\n')
                    for line in lines:
                        if any(kw in line.upper() for kw in ["IMPROVE", "SUGGEST", "SHOULD", "COULD"]):
                            content["suggestions"].append(line.strip())
        except Exception as e:
            print(f"Warning: Could not load reflection file: {e}", file=sys.stderr)

    # Check memory for recent context
    memory_file = Path(f"/Users/kublai/.openclaw/agents/{agent}/memory") / f"{datetime.now().strftime('%Y-%m-%d')}.md"
    if memory_file.exists():
        try:
            with open(memory_file, 'r') as f:
                text = f.read()
                # Extract key points from memory
                lines = text.split('\n')
                for line in lines:
                    line = line.strip()
                    if line.startswith('- ') or line.startswith('* '):
                        content["recent_issues"].append(line[2:])
        except Exception:
            pass

    return content


def generate_proposal_from_template(
    agent: str,
    title: str,
    problem_statement: str,
    proposed_solution: str,
    expected_impact: str,
    implementation_steps: list,
    resource_requirements: str,
    risk_assessment: str,
    success_metrics: list,
    impact: str = "medium",
    effort: str = "medium"
) -> str:
    """Generate a formatted proposal document."""

    agent_info = AGENT_DOMAINS.get(agent, AGENT_DOMAINS["kublai"])
    proposal_id = generate_proposal_id(agent)
    timestamp = datetime.now().isoformat()
    voting_deadline = calculate_voting_deadline()

    return PROPOSAL_TEMPLATE.format(
        proposal_id=proposal_id,
        agent=agent,
        domain=agent_info["domain"],
        timestamp=timestamp,
        voting_deadline=voting_deadline,
        impact=impact,
        effort=effort,
        title=title,
        domain_description=agent_info["domain"],
        problem_statement=problem_statement,
        proposed_solution=proposed_solution,
        expected_impact=expected_impact,
        implementation_steps="\n".join(f"{i+1}. {step}" for i, step in enumerate(implementation_steps)),
        resource_requirements=resource_requirements,
        risk_assessment=risk_assessment,
        success_metrics="\n".join(f"- {m}" for m in success_metrics)
    )


def create_sample_proposals(agent: str) -> list:
    """Create sample proposals based on agent domain for testing/demo."""

    agent_info = AGENT_DOMAINS.get(agent, AGENT_DOMAINS["kublai"])
    proposals = []

    if agent == "temujin":
        proposals.append({
            "title": "Implement Automated Code Quality Gates",
            "problem_statement": "Code quality issues are often caught late in the development cycle, leading to rework and delays.",
            "proposed_solution": "Add pre-commit hooks and CI gates that check code quality, linting, and basic tests before merge.",
            "expected_impact": "Reduce code review cycles by 30%, catch issues earlier, improve code quality metrics.",
            "implementation_steps": [
                "Add pre-commit hook configuration",
                "Configure linters (ruff, black, mypy)",
                "Add CI quality gate workflow",
                "Document quality standards"
            ],
            "resource_requirements": "2-3 hours setup, ongoing maintenance minimal",
            "risk_assessment": "Low risk - standard practice, easy to disable if needed",
            "success_metrics": [
                "Code review cycles reduced by 30%",
                "No decrease in commit velocity",
                "Zero regressions from quality gates"
            ],
            "impact": "high",
            "effort": "low"
        })
    elif agent == "kublai":
        proposals.append({
            "title": "Implement Proposal-Based Task Routing",
            "problem_statement": "Tasks are sometimes routed to agents outside their expertise due to keyword overlap.",
            "proposed_solution": "Add a proposal review step where agents can accept or reject tasks before execution.",
            "expected_impact": "Reduce misroutes by 50%, improve agent autonomy, better task-agent matching.",
            "implementation_steps": [
                "Add task acceptance workflow",
                "Create rejection reason tracking",
                "Update routing algorithm with feedback",
                "Monitor misroute reduction"
            ],
            "resource_requirements": "4-6 hours development, ongoing monitoring",
            "risk_assessment": "Medium risk - may increase latency, requires agent buy-in",
            "success_metrics": [
                "Misroute rate reduced by 50%",
                "Task completion time not increased",
                "Agent satisfaction improved"
            ],
            "impact": "high",
            "effort": "medium"
        })
    elif agent == "ogedei":
        proposals.append({
            "title": "Enhance Health Check Proactive Alerting",
            "problem_statement": "System issues are often detected reactively after they impact operations.",
            "proposed_solution": "Implement proactive alerting based on trend analysis and anomaly detection.",
            "expected_impact": "Reduce incident response time by 40%, prevent issues before impact.",
            "implementation_steps": [
                "Analyze current health metrics",
                "Define alert thresholds and trends",
                "Implement anomaly detection",
                "Create alerting pipeline"
            ],
            "resource_requirements": "3-4 hours development, ongoing tuning",
            "risk_assessment": "Low risk - additive functionality, can be tuned",
            "success_metrics": [
                "Mean time to detection reduced by 40%",
                "False positive rate under 10%",
                "Zero missed critical issues"
            ],
            "impact": "high",
            "effort": "medium"
        })
    elif agent == "jochi":
        proposals.append({
            "title": "Automate Security Vulnerability Scanning",
            "problem_statement": "Security vulnerabilities in dependencies are not consistently tracked or remediated.",
            "proposed_solution": "Implement automated dependency scanning with scheduled reports and remediation tracking.",
            "expected_impact": "Reduce vulnerability exposure time by 60%, improve security posture.",
            "implementation_steps": [
                "Set up dependency scanning tool",
                "Configure scan schedule (daily)",
                "Create vulnerability tracking dashboard",
                "Add remediation workflow"
            ],
            "resource_requirements": "2-3 hours setup, ongoing monitoring",
            "risk_assessment": "Low risk - scanning only, no automated changes",
            "success_metrics": [
                "All critical vulnerabilities remediated within 48h",
                "Scan coverage at 100%",
                "Zero false negatives on known CVEs"
            ],
            "impact": "high",
            "effort": "low"
        })
    elif agent == "mongke":
        proposals.append({
            "title": "Standardize Research Output Format",
            "problem_statement": "Research outputs vary in format and quality, making them harder to consume and act upon.",
            "proposed_solution": "Create standardized research templates with required sections and quality criteria.",
            "expected_impact": "Improve research actionability by 50%, reduce follow-up questions.",
            "implementation_steps": [
                "Design research output template",
                "Define quality criteria checklist",
                "Create example outputs",
                "Update agent documentation"
            ],
            "resource_requirements": "2 hours template design, ongoing refinement",
            "risk_assessment": "Low risk - process improvement, easy to iterate",
            "success_metrics": [
                "All research outputs use standard format",
                "Follow-up questions reduced by 50%",
                "Research utilization rate improved"
            ],
            "impact": "medium",
            "effort": "low"
        })
    elif agent == "chagatai":
        proposals.append({
            "title": "Create Content Style Guide for Kurultai",
            "problem_statement": "Documentation and content lack consistent style, making them harder to read and maintain.",
            "proposed_solution": "Develop a comprehensive style guide covering tone, formatting, and quality standards.",
            "expected_impact": "Improve content quality and consistency, reduce editing cycles.",
            "implementation_steps": [
                "Analyze existing content patterns",
                "Define style guidelines",
                "Create examples and templates",
                "Document in style guide"
            ],
            "resource_requirements": "3-4 hours initial guide, ongoing maintenance",
            "risk_assessment": "Low risk - additive documentation, easy to update",
            "success_metrics": [
                "All new content follows style guide",
                "Editing cycles reduced by 30%",
                "Reader feedback improved"
            ],
            "impact": "medium",
            "effort": "low"
        })

    return proposals


def write_proposal(proposal_content: str, proposal_id: str) -> Path:
    """Write proposal to pending directory."""
    PENDING_DIR.mkdir(parents=True, exist_ok=True)
    proposal_file = PENDING_DIR / f"{proposal_id}.md"

    with open(proposal_file, 'w') as f:
        f.write(proposal_content)

    return proposal_file


def main():
    parser = argparse.ArgumentParser(
        description="Generate proposals for Kurultai consensus voting"
    )
    parser.add_argument(
        "--agent",
        required=True,
        choices=list(AGENT_DOMAINS.keys()),
        help="Agent generating the proposal"
    )
    parser.add_argument(
        "--reflection-file",
        help="Path to agent's recent reflection file"
    )
    parser.add_argument(
        "--sample",
        action="store_true",
        help="Generate sample proposals for testing"
    )
    parser.add_argument(
        "--title",
        help="Proposal title"
    )
    parser.add_argument(
        "--problem",
        help="Problem statement"
    )
    parser.add_argument(
        "--solution",
        help="Proposed solution"
    )

    args = parser.parse_args()

    if args.sample:
        # Generate sample proposals
        proposals = create_sample_proposals(args.agent)
        for p in proposals:
            content = generate_proposal_from_template(
                agent=args.agent,
                title=p["title"],
                problem_statement=p["problem_statement"],
                proposed_solution=p["proposed_solution"],
                expected_impact=p["expected_impact"],
                implementation_steps=p["implementation_steps"],
                resource_requirements=p["resource_requirements"],
                risk_assessment=p["risk_assessment"],
                success_metrics=p["success_metrics"],
                impact=p.get("impact", "medium"),
                effort=p.get("effort", "medium")
            )
            proposal_id = generate_proposal_id(args.agent)
            path = write_proposal(content, proposal_id)
            print(f"Created proposal: {path}")
    else:
        # Generate from provided arguments or interactive
        if args.title and args.problem and args.solution:
            content = generate_proposal_from_template(
                agent=args.agent,
                title=args.title,
                problem_statement=args.problem,
                proposed_solution=args.solution,
                expected_impact="To be determined",
                implementation_steps=["Step 1: Define implementation steps"],
                resource_requirements="To be determined",
                risk_assessment="To be determined",
                success_metrics=["Metric 1: Define success criteria"]
            )
            proposal_id = generate_proposal_id(args.agent)
            path = write_proposal(content, proposal_id)
            print(f"Created proposal: {path}")
        else:
            print("Error: Provide --title, --problem, and --solution, or use --sample")
            sys.exit(1)


if __name__ == "__main__":
    main()